<?php
$escHtml = $this->plugin('escapeHtml');
$escAttr = $this->plugin('escapeHtmlAttr');

$footerLogo      = $this->themeSetting( 'footer_logo' );
$footerSiteInfo  = $this->themeSetting( 'footer_site_info' );
$footerMenu      = $this->themeSetting( 'footer_menu' );
$footerMenuDepth = $this->themeSetting('footer_menu_depth');
$footerContent   = $this->themeSetting( 'footer_content' );
$socialNetworks  = array( 'facebook', 'twitter', 'linkedin', 'instagram', 'youtube', 'mastodon' );

$additional_classes = '';

if ( ! $footerMenu ) {
	$additional_classes .= ' no-menu';
} elseif ( ! $footerLogo && ! $footerSiteInfo && ! $footerContent ) {
	$additional_classes .= ' menu-only';
}

if ( $footerMenu && ( $footerLogo || $footerSiteInfo ) && $footerContent ) {
	$additional_classes .= ' all-columns';

	if ( $footerMenuDepth > 1 ) {
		$additional_classes .= ' menu-depth-2';
	}
}

$hasSocialNetworks = false;

foreach ( $socialNetworks as $social_network ) {
	if ( $this->themeSetting( "{$social_network}_url" ) ) {
		$hasSocialNetworks = true;
		break;
	}
}
?>

<footer class="main-footer">

	<!-- Footer Top (now deleted)-->

	<!-- <hr class="alignfull"> -->

	<!-- Footer Bottom (custom) -->
<div class="main-footer__bottom">
  <div class="container main-footer__bottom-container">

    <div class="main-footer__left">
      <ul class="footer-links footer-links--col">
        <li><a href="/om-forlaget">OM FÖRLAGET</a></li>
        <li><a href="/om-tiden">OM TIDEN</a></li>
      </ul>

      <ul class="footer-links footer-links--col">
        <li><a href="/om-utgivningen">OM UTGIVNINGEN</a></li>
        <li><a href="/om-publikationsserierna">OM PUBLIKATIONSSERIERNA</a></li>
      </ul>

      <ul class="footer-links footer-links--col">
        <li><a href="/om-arkivmaterialet">OM ARKIVMATERIALET</a></li>
        <li><a href="/om-oss">OM OSS</a></li>
      </ul>
    </div>

    <div class="main-footer__right">
      <nav class="footer-partners" aria-label="Partner links">
        <a href="https://www.barnboksinstitutet.se/">SVENSKA BARNBOKSINSTITUTET</a>
        <span class="pipe">|</span>
        <a href="https://www.gu.se/litteratur-idehistoria-religion">LIR</a>
        <span class="pipe">|</span>
        <a href="https://dh.gu.se/">GRIDH</a>
      </nav>
    </div>

  </div>
</div>

</footer>
